package com.xinwei.userOrders.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 用户订单关系表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserOrders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 订单编号. */
	private String orderId;

	/** 订单类型. */
	private String catetory;

	/** 订单业务关键字. */
	private String ownerKey;

	/** 当前步骤状态. */
	private int currentStatus;

	/** 创建时间. */
	private Date createTime;

	/**
	 * Constructor.
	 */
	public UserOrders() {
	}

	/**
	 * Set the 订单编号.
	 * 
	 * @param orderId
	 *            订单编号
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * Get the 订单编号.
	 * 
	 * @return 订单编号
	 */
	public String getOrderId() {
		return this.orderId;
	}

	/**
	 * Set the 订单类型.
	 * 
	 * @param catetory
	 *            订单类型
	 */
	public void setCatetory(String catetory) {
		this.catetory = catetory;
	}

	/**
	 * Get the 订单类型.
	 * 
	 * @return 订单类型
	 */
	public String getCatetory() {
		return this.catetory;
	}

	/**
	 * Set the 订单业务关键字.
	 * 
	 * @param ownerKey
	 *            订单业务关键字
	 */
	public void setOwnerKey(String ownerKey) {
		this.ownerKey = ownerKey;
	}

	/**
	 * Get the 订单业务关键字.
	 * 
	 * @return 订单业务关键字
	 */
	public String getOwnerKey() {
		return this.ownerKey;
	}

	/**
	 * Set the 当前步骤状态.
	 * 
	 * @param currentStatus
	 *            当前步骤状态
	 */
	public void setCurrentStatus(int currentStatus) {
		this.currentStatus = currentStatus;
	}

	/**
	 * Get the 当前步骤状态.
	 * 
	 * @return 当前步骤状态
	 */
	public int getCurrentStatus() {
		return this.currentStatus;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}


}
