package com.xinwei.orderDb.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of order_flow.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OrderFlow implements Serializable {

	// 订单初始化状态
	public static final int STATUS_initial = 0;

	// 订单运行状态
	public static final int STATUS_running = 1;

	// 订单挂起状态
	public static final int STATUS_suspend = 2;

	// 订单终止状态（不继续执行）
	public static final int STATUS_terminate = 3;

	// 订单正常结束状态
	public static final int STATUS_ending = 4;

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 分区ID. */
	private String partitionId;

	/** 订单编号. */
	private String orderId;
	/** 订单类型. */
	private String catetory;
	
	/** 订单业务关键字. */
	private String ownerKey;

	/** 订单步骤ID. */
	private String stepId;

	/** 流程ID. */
	private String flowId;

	/** 创建时间. */
	private Date createTime;

	/** 最新更新时间. */
	private Date updateTime;

	/** 订单上下文数据关键字. */
	private String dataKey;

	/** 订单上下文数据. */
	private String contextData;

	/** 任务重做次数. */
	private String retryTimes;

	/** 当前步骤状态. */
	private int currentStatus;

	/** 错误和描述. */
	private String retCode;

	/** 错误和描述. */
	private String retMsg;

	/**
	 * Constructor.
	 */
	public OrderFlow() {
	}

	/**
	 * Set the 分区ID.
	 * 
	 * @param partitionId
	 *            分区ID
	 */
	public void setPartitionId(String partitionId) {
		this.partitionId = partitionId;
	}

	/**
	 * Get the 分区ID.
	 * 
	 * @return 分区ID
	 */
	public String getPartitionId() {
		return this.partitionId;
	}

	/**
	 * Set the 订单编号.
	 * 
	 * @param orderId
	 *            订单编号
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
		this.partitionId = orderId.substring(orderId.length() - 7, orderId.length() - 4);
		
	}

	/**
	 * Get the 订单编号.
	 * 
	 * @return 订单编号
	 */
	public String getOrderId() {
		return this.orderId;
	}

	/**
	 * Set the 订单业务关键字.
	 * 
	 * @param ownerKey
	 *            订单业务关键字
	 */
	public void setOwnerKey(String ownerKey) {
		this.ownerKey = ownerKey;
	}

	/**
	 * Get the 订单业务关键字.
	 * 
	 * @return 订单业务关键字
	 */
	public String getOwnerKey() {
		return this.ownerKey;
	}

	/**
	 * Set the 订单步骤ID.
	 * 
	 * @param stepId
	 *            订单步骤ID
	 */
	public void setStepId(String stepId) {
		this.stepId = stepId;
	}

	/**
	 * Get the 订单步骤ID.
	 * 
	 * @return 订单步骤ID
	 */
	public String getStepId() {
		return this.stepId;
	}

	/**
	 * Set the 流程ID.
	 * 
	 * @param flowId
	 *            流程ID
	 */
	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	/**
	 * Get the 流程ID.
	 * 
	 * @return 流程ID
	 */
	public String getFlowId() {
		return this.flowId;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 最新更新时间.
	 * 
	 * @param updateTime
	 *            最新更新时间
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 最新更新时间.
	 * 
	 * @return 最新更新时间
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the 订单上下文数据关键字.
	 * 
	 * @param dataKey
	 *            订单上下文数据关键字
	 */
	public void setDataKey(String dataKey) {
		this.dataKey = dataKey;
	}

	/**
	 * Get the 订单上下文数据关键字.
	 * 
	 * @return 订单上下文数据关键字
	 */
	public String getDataKey() {
		return this.dataKey;
	}

	/**
	 * Set the 订单上下文数据.
	 * 
	 * @param contextData
	 *            订单上下文数据
	 */
	public void setContextData(String contextData) {
		this.contextData = contextData;
	}

	/**
	 * Get the 订单上下文数据.
	 * 
	 * @return 订单上下文数据
	 */
	public String getContextData() {
		return this.contextData;
	}

	/**
	 * Set the 任务重做次数.
	 * 
	 * @param retryTimes
	 *            任务重做次数
	 */
	public void setRetryTimes(String retryTimes) {
		this.retryTimes = retryTimes;
	}

	/**
	 * Get the 任务重做次数.
	 * 
	 * @return 任务重做次数
	 */
	public String getRetryTimes() {
		return this.retryTimes;
	}

	/**
	 * Set the 当前步骤状态.
	 * 
	 * @param currentStatus
	 *            当前步骤状态
	 */
	public void setCurrentStatus(int currentStatus) {
		this.currentStatus = currentStatus;
	}

	/**
	 * Get the 当前步骤状态.
	 * 
	 * @return 当前步骤状态
	 */
	public int getCurrentStatus() {
		return this.currentStatus;
	}

	/**
	 * Set the 错误和描述.
	 * 
	 * @param retCode
	 *            错误和描述
	 */
	public void setRetCode(String retCode) {
		this.retCode = retCode;
	}

	/**
	 * Get the 错误和描述.
	 * 
	 * @return 错误和描述
	 */
	public String getRetCode() {
		return this.retCode;
	}

	/**
	 * Set the 错误和描述.
	 * 
	 * @param retMsg
	 *            错误和描述
	 */
	public void setRetMsg(String retMsg) {
		this.retMsg = retMsg;
	}

	/**
	 * Get the 错误和描述.
	 * 
	 * @return 错误和描述
	 */
	public String getRetMsg() {
		return this.retMsg;
	}

	
	public String getCatetory() {
		return catetory;
	}

	public void setCatetory(String catetory) {
		this.catetory = catetory;
	}

	@Override
	public String toString() {
		return "OrderFlow [partitionId=" + partitionId + ", orderId=" + orderId + ", ownerKey=" + ownerKey + ", stepId="
				+ stepId + ", flowId=" + flowId + ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", dataKey=" + dataKey + ", contextData=" + contextData + ", retryTimes=" + retryTimes
				+ ", currentStatus=" + currentStatus + ", retCode=" + retCode + ", retMsg=" + retMsg + "]";
	}

}
